version: "3.9"

services:
  db:
    image: postgres:16
    container_name: doc_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - doc_network

  web:
    build: .
    container_name: doc_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - doc_network

  nginx:
    image: nginx:stable-alpine
    container_name: doc_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - ./nginx/certbot:/app/certbot:rw
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web
    networks:
      - doc_network

  certbot:
    image: certbot/certbot
    container_name: doc_certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot:/app/certbot:rw
      - ./certs:/etc/ssl/certs
    entrypoint: >
      sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /app/certbot --quiet; done"
    networks:
      - doc_network

networks:
  doc_network:

volumes:
  postgres_data:
  static_volume:
