databases:
  - name: docs_db_hurf
    plan: free # Free tier database expires after 90 days

services:
  - type: web
    name: drf_api # A descriptive name
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /api/v1/health # Example health check endpoint
    preDeployCommand: "python manage.py migrate"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: docs_db_hurf
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure key for you
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "drf-api.onrender.com" # Update with your service name
      - key: DJANGO_ALLOWED_HOSTS
        value: "docs-backend-x9ra.onrender.com"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      # IMPORTANT: Sensitive variables should not be in this file.
      # You must add these in the Render dashboard for the service.
      # These are placeholders to show what keys are needed.
      - key: DJANGO_EMAIL_HOST_USER
        value: "" # Add in Render dashboard
      - key: DJANGO_EMAIL_HOST_PASSWORD
        value: "" # Add in Render dashboard
      - key: AZAMPAY_CLIENT_ID
        value: "" # Add in Render dashboard
      - key: AZAMPAY_CLIENT_SECRET
        value: "" # Add in Render dashboard
      - key: STRIPE_TEST_SECRET_KEY
        value: "" # Add in Render dashboard
      - key: OPENROUTER_API_KEY
        value: "" # Add in Render dashboard
