# Generated by Django 5.2.4 on 2025-08-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usertb_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertb',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='usertb',
            name='role',
        ),
    ]
